### ISSUE TITLE
sydneyhud 

### ISSUE THREAD

**Issue by repoman728** [dominikvyhnak/SydneyHUDFix#1]
Hi 
I have put Syndeyhud file in mod folder , started the game and nothing , it is in blt mods list but nowhere else . in heist , there is nothing  no hud , any ideas ?

**Comment by dominikvyhnak** [comment]
Hi. Can you post here BLT log ?

**Comment by repoman728** [comment]
Here we go 
[2018_11_17_log.txt](https://github.com/dominikvyhnak/SydneyHUDFix/files/2592151/2018_11_17_log.txt)

**Comment by dominikvyhnak** [comment]
Your log showed a lot of errors. A lot of them can be fixed by deleting unnecessary comma. Your log also showed why SydneyHUD is not working. It tries to load saved settings but it failes for some reason. Can you try deleting SydneyHUD saved settings in /mods/saves folder and try it again ?

**Comment by repoman728** [comment]
ok  will do 
thanks for help

**Comment by repoman728** [comment]
it is working now , thanks again for help. there  is another thing like on the picture only th black line in the is original hud - How I can fixed that?
![syd](https://user-images.githubusercontent.com/31778610/48670849-0afb5080-eb30-11e8-9a1f-92f6a43a8cd5.JPG)

**Comment by dominikvyhnak** [comment]
I'm not sure what are talking right now. It's the black line on your HUD when you are playing or it is a different issue you are trying to describe me?

**Comment by repoman728** [comment]
sorry  for it , it is like hud over the hud - right corner  I will make real screen later

**Comment by dominikvyhnak** [comment]
> sorry for it , it is like hud over the hud - right corner I will make real screen later

Is the issue still relevant ? Or should I go ahead and lock this ?

**Comment by dominikvyhnak** [comment]
Locked due to inactivity.
