### ISSUE TITLE
the download stays in Verifying

### ISSUE THREAD

**Issue by SaveMeOh** [dominikvyhnak/SydneyHUDFix#20]
it's a bit annoying come into the game and see that the mod needs to be updated, once the mod is downloaded it stays frozen in checking...
It still works, but every time I enter I see that it needs to be updated.

Pls I need help

**Comment by dominikvyhnak** [comment]
Which BLT you have ? Normal one or Super ?

**Comment by GFNimbuscloud** [comment]
I'm having the same issue, and I switched to the Super BLT.  I also have to hold "f" to interact for some reason, no matter whether that option it ticked or unticked, and the health regen from grinder doesn't seem to be working.

**Comment by dominikvyhnak** [comment]
I fixed it by removing updates for beta version in commit https://github.com/dominikvyhnak/SydneyHUDFix/commit/4457edde37d14d0e5810a326c5839f7ec516625c.

If you want to stay updated, download public version from here:
https://modworkshop.net/mydownloads.php?action=view_down&did=23831
