### ISSUE TITLE
Crash mostly on lobby close

### ISSUE THREAD

**Issue by averon420** [dominikvyhnak/SydneyHUDFix#21]
Hello, my friend and me using same mods, he crashes alot, when I host and I abort mission or close the lobby.

`06:10:53 PM FATAL ERROR:  (C:\Users\ZNix\source\repos\SuperBLT\src\InitiateState.cpp:314) mods/SydneyHUD/lua/lib/managers/HUDManager.lua:89: attempt to index field 'game_settings' (a nil value)
stack traceback:
    mods/SydneyHUD/lua/lib/managers/HUDManager.lua:89: in function 'FixNames'
    mods/SydneyHUD/lua/lib/managers/HUDManager.lua:137: in main chunk
    [C]: in function 'dofile'
    mods/base/base.lua:132: in function 'RunHookFile'
    mods/base/base.lua:124: in function 'RunHookTable'
    mods/base/base.lua:154: in function 'require'
    mods/More Weapon Stats/lua/menushotgunbase.lua:6: in main chunk
    [C]: in function 'dofile'
    mods/base/base.lua:132: in function 'RunHookFile'
    mods/base/base.lua:124: in function 'RunHookTable'
    mods/base/base.lua:152: in function 'require'
    [string "lib/setups/menusetup.lua"]:19: in main chunk
    [C]: in function 'require'
    mods/base/base.lua:153: in function 'require'
    [string "lib/entry.lua"]:13: in main chunk
    [C]: in function 'require'
    mods/base/base.lua:153: in function 'require'
    [string "core/lib/coreentry.lua"]:19: in main chunk`

**Comment by dominikvyhnak** [comment]
Post here crashlog instead.

**Comment by averon420** [comment]
> Post here crashlog instead.

Can I send you the log file per PM?

**Comment by dominikvyhnak** [comment]
> Can I send you the log file per PM?
You can attach the log here.

I'll be able to download it and investigate.

Just drop the files to this edit box.

**Comment by averon420** [comment]
[2020_01_20_log (1).txt](https://github.com/dominikvyhnak/SydneyHUDFix/files/4141960/2020_01_20_log.1.txt)

can you delete it afterwards? Thanks for your effort on fixing the bug. :)

**Comment by dominikvyhnak** [comment]
366d8f99769a035460481749f06081680200bb8a should fix that.

Thanks for the report
