### ISSUE TITLE
Modify laser color

### ISSUE THREAD

**Issue by Nazrin720** [dominikvyhnak/SydneyHUDFix#26]
I want to modify the laser color of the sniper, but the menu is not displayed completely
![QQ截图20200709161521](https://user-images.githubusercontent.com/63951577/87015283-cab67d80-c1ff-11ea-8584-a50136f8e247.png)
Just like the picture, is this normal, my monitor is 2560×1080

**Comment by dominikvyhnak** [comment]
Fixed in https://github.com/dominikvyhnak/SydneyHUDFix/commit/1f181a61a9ad4c5eee4237d85a3e363f4a1a9ad5
